name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR
        run: docker login --username=${{ secrets.ACR_USERNAME }} --password=${{ secrets.ACR_PASSWORD }} ${{ secrets.ACR_REGISTRY }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_REPOSITORY }}:${{ github.sha }} # 镜像标签，你可以根据需要调整
          cache-from: type=registry,ref=${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_REPOSITORY }}:latest
          cache-to: type=registry,ref=${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_REPOSITORY }}:latest,mode=max

      - name: Push latest tag
        run: docker push ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_REPOSITORY }}:latest
